sithlord48/ff7tk

.github/workflows/build.yml, src/data/FF7Save.cpp, src/data/FF7Save.h, src/data/FF7SaveInfo.cpp, src/data/FF7SaveInfo.h, src/widgets/MetadataCreator.cpp, src/widgets/SlotSelect.cpp
clean up the export methods so that common code can be shared between 3 export types
exportPCFormat <- handles PC types, Switch and PC
exportVMCFormat <- handles VMC type, vmc, psp, dex, vgs 
exportSlot <- export a single slot type. PSX , PS3, PGE PDA types. 
Rename `FF7SaveInfo::internalPC` to `FF7SaveInfo::isTypePC` <- Is a FF7SaveInfo::FORMAT a PC format save (PC, SWITCH)
New Methods
- `FF7SaveInfo::isVirtualMemoryCard(FF7SaveInfo::FORMAT)`
- `FF7SaveInfo::vmcHeaderOffset(FF7SaveInfo::FORMAT)`
- `FF7SaveInfo::isTypeVMC(FF7SaveInfo::FORMAT)`
- `FF7SaveInfo::isTypeSSS(FF7SaveInfo::FORMAT)`
- `FF7SaveInfo::psxSaveNameOffset(FF7SaveInfo::FORMAT)`
FF7Save. Clean up by using the new methods. Update other objects needing update for name change
=> Export cleanup

src/data/Type_FF7CHAR.h, src/data/ff7tkAbout.h.in, src/widgets/CharEditor.cpp
Type_FF7Char
- Initialize with EmptyID
CharacterEditor 
- Reset selected materia slot on when character character changes
- Allow Combo Id's Menu to show all Id entries at once.
Misc
- Remove Qt Version from ff7tk_version String
=> Improvements to FF7Character classes.

src/data/FF7Materia.cpp, src/data/FF7Materia.h, src/data/FF7Save.cpp, src/data/Type_materia.h, src/widgets/CharEditor.cpp, src/widgets/MateriaEditor.cpp
`FF7Materia` Changes
- Rename `FF7Materia::ap` to `FF7Materia::apForLevel`
- Added `materia FF7Materia::encodeMateria(id, ap)`
- Added `int FF7Materia::materiaID(materia)`
- Replace  `qint32 FF7Materia::ap2num (quint8[3])` with several methods
- `qint32 FF7Materia::materiaAP(materia)`
- `qint32 FF7Materia::materiaAP(quint8, quint8, quint8)`
- `qint32 FF7Materia::materiaAP(quint8 [3])`
Use new methods to replace old code. in `FF7Save` , `CharEditor` and `MateriaEditor`
=> FF7Materia cleanup and update

packaging/cpackOptions.cmake.in
- [Win32] Fix up build to ship qml imports when windepoyqt is run on the demo projects.
=> Run qmlimportscanner on demo projects only

demos/ff7tkWidgetGallery/CMakeLists.txt, demos/ff7tkWidgetGallery/mainwindow.cpp, demos/ff7tkWidgetGallery/mainwindow.h, demos/ff7tkWidgetGallery/mainwindow.ui, src/icons/common.qrc, src/icons/common/edit-cut.svg, src/icons/common/go-down.svg, src/icons/common/go-up.svg, src/icons/common/list-add.svg, src/icons/common/list-remove.svg, src/widgets/common/CMakeLists.txt, src/widgets/common/ImageGridWidget.cpp, src/widgets/common/ImageGridWidget.h, src/widgets/common/ListWidget.cpp, src/widgets/common/ListWidget.h, src/widgets/common/OrientationWidget.cpp, src/widgets/common/OrientationWidget.h, translations/ff7tk_de.ts, translations/ff7tk_en.ts, translations/ff7tk_es.ts, translations/ff7tk_fr.ts, translations/ff7tk_it.ts, translations/ff7tk_ja.ts, translations/ff7tk_pl.ts, translations/ff7tk_re.ts
Done so far: 
- Import OrientationWidget
- Member of `ff7tkQtWidgets`
- Improve text label location and scaling
- `Q_EMIT` replace `emit`
- Provide Two "Styles" [Grid, Arrow]  
-  <img src ="https://user-images.githubusercontent.com/7450820/219149336-aff82dff-4f60-4022-9a63-b8c3f5722838.png" width="450" height="200"></img>
- Allow for Rotation Direction Change
- Allow for Zero to be North , South , East or West
- Import ListWidget
- Add ff7tk common icons to support actions in list widget
- Aware of Language Changes.
- Import ImageGridWidget
- `Q_EMIT` replace emit
=> Stage For next Merge from Makou

src/data/SaveIcon.cpp, src/widgets/data/AchievementEditor.cpp, src/widgets/data/AchievementEditor.h, src/widgets/data/CharEditor.cpp, src/widgets/data/CharEditor.h, src/widgets/data/ChocoboEditor.cpp, src/widgets/data/ChocoboLabel.cpp, src/widgets/data/ChocoboLabel.h, src/widgets/data/ChocoboManager.cpp, src/widgets/data/ChocoboManager.h, src/widgets/data/MateriaEditor.cpp, src/widgets/data/MateriaEditor.h, src/widgets/data/SlotPreview.cpp, src/widgets/data/SlotPreview.h, src/widgets/data/SlotSelect.cpp, translations/ff7tk_it.ts
No Palette Change Before: 
- Rewrite SlotPreview to use painter and be palette aware
- Reworked the chocobo Widgets so they are more plaette aware
Find and  Fix up Color uses stylesheets :
- Materia Editor use palette to get highlight
Remove Extra Large indicators and let the system style size and place them
=> Palette fixes

demos/ff7tkQmlGallery/MateriaSlotButton.qml, demos/ff7tkQmlGallery/main.cpp, docs/build.md, src/core/CMakeLists.txt, src/core/ff7tkConfig.cmake.in, src/core/ff7tkInfo.h.in, src/data/CMakeLists.txt, src/data/FF7Char.cpp, src/data/FF7Char.h, src/data/FF7FieldItemList.cpp, src/data/FF7FieldItemList.h, src/data/FF7Item.cpp, src/data/FF7Item.h, src/data/FF7Location.cpp, src/data/FF7Location.h, src/data/FF7Materia.cpp, src/data/FF7Materia.h, src/data/FF7SaveInfo.cpp, src/data/FF7SaveInfo.h, src/data/FF7Text.cpp, src/data/FF7Text.h, src/data/ff7tkDataConfig.cmake.in, unittests/data/FF7Text_test.cpp
-   DEPRECATED singleton `instance` methods use `get` instead
-  Update Qml Exposure to newer QtQmlIntegration methods.
=> Update Qml Exposure

src/data/CMakeLists.txt, src/data/FF7String.cpp, src/data/FF7String.h
Add a new class `FF7String` to the `ff7tkData` Library. 
This Class is a based upon the class of the same in from [Makou Reactor](https://github.com/myst6re/makoureactor) and is intended to be its successor. It stores text in FF7Data format and provides some convenience methods so you can use it as you would a normal string class. 
Changes from the makou Version 
- Its backed by The FF7Text object 
- Stores the  if its a japanese string internally. just call `text()` for the pc string. Note: The `QByteArray` constructor uses `FF7Text::isJapanese()` to set this. 
- `setJapanese` and `isJapanese` methods so you can get / set the fonts set used for the string.
=> New FF7String Class

cmake/ff7tkMacros.cmake, demos/ff7tkQmlGallery/CMakeLists.txt, demos/ff7tkQmlGallery/TextDemo.qml, demos/ff7tkQmlGallery/main.cpp, demos/ff7tkQmlGallery/main.qml, demos/ff7tkQmlGallery/qml.qrc, src/CMakeLists.txt, src/data/FF7Item.cpp, src/data/FF7Materia.h, src/ff7tkQuick/CMakeLists.txt, src/ff7tkQuick/Controls/CMakeLists.txt, src/ff7tkQuick/Controls/Components/ComboBox.qml, src/ff7tkQuick/Controls/ItemPreview.qml, src/ff7tkQuick/Controls/MateriaEditor.qml, src/ff7tkQuick/Controls/MateriaSlotButton.qml, src/ff7tkQuick/Controls/ff7tkQuickControlsConfig.cmake.in, src/ff7tkQuick/DataTypes/CMakeLists.txt, src/ff7tkQuick/DataTypes/ff7tkQuickDataTypes.h, src/ff7tkQuick/DataTypes/ff7tkQuickDataTypesConfig.cmake.in
Begin #126 
-  New QML Module `ff7tkQuickData` to expose data items and ff7tkInfo
- `ff7tkInfo` is Exposed  as `FF7tkInfo` 
- Exposes `FF7Item`, `FF7Text`, `FF7Materia` from libff7tkData
- New QML Module `ff7tkQuickControls` for QML based controls
- ItemPreview - Preview an items info
- MateriaSlot - a materia slot that can hold a materia
- MateriaEditor - The Start of materia selector / editor.
- Currently contains style items for  ComboBox
=> FF7tk controls

demos/ff7tkQmlGallery/TextDemo.qml, demos/ff7tkQmlGallery/main.qml, src/ff7tkQuick/Controls/CMakeLists.txt, src/ff7tkQuick/Controls/Components/ApplicationWindow.qml, src/ff7tkQuick/Controls/Components/Button.qml, src/ff7tkQuick/Controls/Components/CheckBox.qml, src/ff7tkQuick/Controls/Components/ComboBox.qml, src/ff7tkQuick/Controls/Components/Label.qml, src/ff7tkQuick/Controls/Components/ToolTip.qml, src/ff7tkQuick/Controls/MateriaEditor.qml, src/ff7tkQuick/Controls/MateriaSelector.qml, translations/ff7tk_de.ts, translations/ff7tk_en.ts, translations/ff7tk_es.ts, translations/ff7tk_fr.ts, translations/ff7tk_it.ts, translations/ff7tk_ja.ts, translations/ff7tk_pl.ts, translations/ff7tk_re.ts
Closes #126 
- New base Qml Components
- Use the base components in the ff7tkQuick.Controls
=> Qml: Base Components for Controls

src/data/FF7FieldItemList.h
Fix typo from `sundun_1` => `sandun_1`
=> sundun_1 => sandun_1

.github/workflows/build.yml
Update Actions used for the github runner
- Checkout 3 => 4
- install-qt-action 3 => 3.3.0 (needs 
- upload 3 => 4
- download 3 => 4
- github-pages-deploy 4.4.1 => 4.5
- cache 3.0.11 => 4
- run-on-arch-action 2.3.0 => 2.6.0
=> update GH Actions

src/formats/Lgp.cpp, src/formats/Lgp_p.cpp, src/formats/TblFile.cpp, src/formats/TexFile.cpp, src/formats/TimFile.cpp, src/formats/WindowBinFile.cpp, src/utils/GZIP.cpp, src/utils/GZIPPS.cpp, src/utils/LZS.cpp, src/utils/PsfFile.cpp, src/widgets/common/QTaskBarButton.cpp
- Remove the C Style Casts for Cpp ones.
=> clean up C Casts

.github/workflows/build.yml, cmake/sbom.cmake
- Fix generated sbom to be ntia compliant, reenable checking of compliance on ci.
=> build: Generated SBOM is once again NTIA compliant

src/widgets/data/ItemListView.cpp, src/widgets/data/ItemSelector.cpp, src/widgets/data/MateriaEditor.cpp, src/widgets/data/OptionsWidget.cpp
Improve the sizes for items in a more theme independent way
- ItemSelector / ItemListView  width
- Option Dialog's Controller mapping combo boxes
- Materia Editor  Better default height of the skill box for themes that use padding
=> Widgets: Better adjust for various widget styles

src/widgets/data/LocationViewer.cpp, translations/ff7tk_de.ts, translations/ff7tk_fr.ts
- Fix locationViewer to correctly search for non english strings
=> fix: locationWidget search for non english

src/widgets/common/DoubleCheckBox.cpp, src/widgets/common/DoubleCheckBox.h, src/widgets/data/CharEditor.cpp, src/widgets/data/CharEditor.h, src/widgets/data/MenuListWidget.cpp, src/widgets/data/PhsListWidget.cpp, src/widgets/data/SlotPreview.cpp, src/widgets/data/SlotPreview.h, src/widgets/data/SlotSelect.cpp
=> Uniform signal style

src/data/FF7Save.cpp, src/data/FF7Save.h
`FF7Save::importSlot()` now returns a bool to indicate if the slot was successfully imported.
=> FF7Save::importSlot returns bool now

src/data/FF7Save.cpp, src/data/FF7SaveInfo.cpp, src/data/FF7SaveInfo.h
Turns out alot of things dont' even write a header into the DEX (.gme) files so loading was failing on those. To resolve this check for DEX format last and only verify the size is correct.
=> fix: GME loading

src/data/FF7FieldItemList.h, src/ff7tkQuick/Controls/Components/CheckBox.qml, translations/ff7tk_de.ts, translations/ff7tk_en.ts, translations/ff7tk_es.ts, translations/ff7tk_fr.ts, translations/ff7tk_it.ts, translations/ff7tk_ja.ts, translations/ff7tk_pl.ts, translations/ff7tk_re.ts
fixes: #182
fixes: #183 
-  Add Snowboard mini-game rewards to the fieldItem List
-  Update QML checkbox  style
=> Fix: mising snowboard mini game rewards on `games_2`

src/data/FF7Save.cpp
- Fix arg parsing in q6.9 (cant' give arg a char? )
=> fix: build for Qt 6.9

.github/workflows/build.yml
- Update to use v4.3.0 of install-qt-action
- Use Qt 6.9.1 to build
- Requires Msvc 2022 for windows
- Remove un-neeed ninja install from ci runners (its pre installed now)
=> ci: Update Qt

src/ff7tk/ff7tkInfo.h.in
Replaces substring extraction with a regular expression to more accurately parse language codes from translation filenames. This ensures support for both two-letter and region-specific language codes.
=> Improve language code extraction in translation loader
