sithlord48/ff7tk

- ff7tkWidgetGallery/mainwindow.ui
- lang/CMakeLists.txt
- lang/ff7tk_de.ts
- lang/ff7tk_en.ts
- lang/ff7tk_es.ts
- lang/ff7tk_fr.ts
- lang/ff7tk_ja.ts
- lang/ff7tk_pl.ts
- lang/ff7tk_re.ts
Add Polish translations
Small change title in form(typo)
> Add Polish translations and small change

- .github/workflows/build.yml
- CMakeLists.txt
- ff7tkQmlGallery/main.cpp
- ff7tkWidgetGallery/mainwindow.cpp
- src/data/CMakeLists.txt
- src/data/FF7Materia.h
- src/data/FF7SaveInfo.cpp
- src/data/FF7SaveInfo.h
- src/data/ff7tkAbout.h.in
- src/widgets/LocationViewer.cpp
- src/widgets/MateriaEditor.cpp
Stage for next round of updates.
> Misc Updates

- lang/ff7tk_it.ts
As per title, i updated and added translations across most sections, Locations being the major exclusion. Left some notes here and there you might want to check.
> Updated most sections but Locations

- src/data/CMakeLists.txt
- src/data/crypto/CMakeLists.txt
- src/data/crypto/aes.c
- Move AES Crypto to a static lib
> Build AES into static lib

- src/data/FF7Save.cpp
- src/data/FF7SaveInfo.h
- src/data/SaveIcon.cpp
- SaveIcon emits nextIcon on setAll
- FF7Save Relax Switch Detection
> Various Fixes

- demos/ff7tkWidgetGallery/mainwindow.cpp
- demos/ff7tkWidgetGallery/mainwindow.h
- demos/ff7tkWidgetGallery/mainwindow.ui
- lang/ff7tk_de.ts
- lang/ff7tk_en.ts
- lang/ff7tk_es.ts
- lang/ff7tk_fr.ts
- lang/ff7tk_it.ts
- lang/ff7tk_ja.ts
- lang/ff7tk_pl.ts
- lang/ff7tk_re.ts
- src/data/CMakeLists.txt
- src/data/FF7Item.h
- src/data/FF7ItemModel.cpp
- src/data/FF7ItemModel.h
- src/widgets/CMakeLists.txt
- src/widgets/ItemListView.cpp
- src/widgets/ItemListView.h
- src/widgets/ItemSelectionDelegate.cpp
- src/widgets/ItemSelectionDelegate.h
- src/widgets/ItemSelector.cpp
- src/widgets/ItemSelector.h
- New FF7ItemModel
- New ItemSelectionDelegate
- New ItemListView 
- ItemList is now deprecated will be removed in
> New ItemListView

- lang/ff7tk_de.ts
- lang/ff7tk_en.ts
- lang/ff7tk_es.ts
- lang/ff7tk_fr.ts
- lang/ff7tk_it.ts
- lang/ff7tk_ja.ts
- lang/ff7tk_pl.ts
- lang/ff7tk_re.ts
- src/formats/CMakeLists.txt
- src/formats/IsoArchiveFF7.cpp
- src/formats/IsoArchiveFF7.h
- src/formats/TexFile.cpp
- src/formats/TexFile.h
- src/formats/TextureFile.cpp
- src/formats/TextureFile.h
- src/formats/TimFile.cpp
- src/formats/TimFile.h
- src/formats/WindowBinFile.cpp
- src/formats/WindowBinFile.h
- src/utils/QLockedFile.cpp
- src/utils/QLockedFile.h
- src/widgets/common/CMakeLists.txt
- src/widgets/common/ColorDisplay.cpp
- src/widgets/common/ColorDisplay.h
- src/widgets/common/QTaskBarButton.cpp
- src/widgets/common/QTaskBarButton.h
- src/widgets/common/QTaskBarButton.mm
Merge Items from Makou Reactor
- `ff7tkQtWidgets::ColorDisplay`
- `ff7tkQtWidgets::QTaskBarButton`
- `ff7tkFormats::TextureFile`
- `ff7tkFormats::TexFile`
- `ff7tkFormats::TimFile`
- `ff7tkFormats::IsoArchiveFF7`
- `ff7tkFormats::WindowBinFile`
> Makou merge1

- CMakeLists.txt
- src/formats/Akao.cpp
- src/formats/Akao.h
- src/formats/AkaoIO.cpp
- src/formats/AkaoIO.h
- src/formats/CMakeLists.txt
- src/formats/TblFile.cpp
- src/formats/TblFile.h
- src/utils/CMakeLists.txt
- src/utils/IO.cpp
- src/utils/IO.h
- src/widgets/common/CMakeLists.txt
- src/widgets/common/HexLineEdit.cpp
- src/widgets/common/HexLineEdit.h
- Add more stuff from makou
- update version to 0.82.1
> Makou merge2

- src/data/FF7ItemModel.cpp
- src/data/FF7ItemModel.h
- src/data/crypto/aes.c
- FF7ItemModel Add resetItems to set initialItems after creation.
- tidy up aes.c
> More updates

- .github/workflows/build.yml
- Add code QL check into the deb build step
> Add CodeQL Checks

- src/data/FF7Save.h
- src/data/FF7SaveInfo.h
> Minor Code Cleanup

- .github/workflows/build.yml
- CMakeLists.txt
Fixes #113 
And Stages Release
> Adjust pkgconfig and cmake Install Paths

- .github/workflows/build.yml
- Lower min MacOS Requirement to 10.14
> with with mac os 10.14+

- .github/workflows/build.yml
- demos/ff7tkQmlGallery/ComboBox.qml
- demos/ff7tkQmlGallery/ItemPreview.qml
- demos/ff7tkQmlGallery/MateriaEditor.qml
- demos/ff7tkQmlGallery/MateriaSlotButton.qml
- demos/ff7tkQmlGallery/TextDemo.qml
- demos/ff7tkQmlGallery/main.qml
- demos/ff7tkQmlGallery/qml.qrc
- src/data/FF7Materia.h
- Add Copyright to qml files
- New QML Items 
- Combobox style 
- Materia Slot
- Materia Preview (WIP) 
- Qt IFW 4.6
> Materia preview start

- src/data/FF7Achievements.cpp
- src/data/FF7Char.cpp
- src/data/FF7FieldItemList.cpp
- src/data/FF7Item.cpp
- src/data/FF7Location.cpp
- src/data/FF7Materia.cpp
- src/data/FF7Materia.h
- src/widgets/data/MateriaEditor.cpp
- translations/ff7tk_ja.ts
Use toUtf8 in place of toLocal8Bit
> Use toUtf8

- translations/ff7tk_en.ts
- translations/ff7tk_ja.ts
- translations/ff7tk_re.ts
- Fix some minor translation statuses in ts files
- Fix RedXIII's Default Japanese Name to `レッド⑬`
> Various Translation Corrections

- CMakeLists.txt
- packaging/CMakeLists.txt
> Release 0.83.3

- .github/workflows/build.yml
- CMakeLists.txt
- [CMake] Better Detect and use available cores.
- [CI] Use Ninja to build
> [CMake] Better Detect and use available cores.

- .github/workflows/build.yml
- CMakeLists.txt
- docs/CMakeLists.txt
- src/data/crypto/CMakeLists.txt
- Use `Ninja` generator on linux 
- Use `Clang` to build on linux
- Pick a better linker when using `gcc` or `clang`
- Slience Doxygen output
- Update `Zlib` to 1.3 for Windows Ci
- Update Qt to 6.5.3
> Build Faster

- .github/workflows/build.yml
- demos/ff7tkWidgetGallery/mainwindow.cpp
- demos/ff7tkWidgetGallery/mainwindow.h
- demos/ff7tkWidgetGallery/mainwindow.ui
- src/core/ff7tkInfo.h.in
- src/data/FF7Char.cpp
- src/formats/IsoArchive.cpp
- src/formats/IsoArchiveFF7.cpp
- src/formats/Lgp.cpp
- src/utils/PsfFile.cpp
- src/widgets/common/EncounterTableWidget.cpp
- src/widgets/data/CharEditor.cpp
- src/widgets/data/ItemList.cpp
- src/widgets/data/ItemPreview.cpp
- src/widgets/data/MateriaEditor.cpp
- Use Qt 6.6.0 
- Replace qAsConst with std::as_const
- Can not make non member connection unique
> Dep cleanup

- src/data/FF7Text.cpp
- src/data/FF7Text.h
- unittests/data/FF7Text_test.cpp
- unittests/data/FF7Text_test.h
> Allow lowercase tags in FF7Text

- .reuse/dep5
- CMakeLists.txt
- cmake/ff7tkMacros.cmake
- demos/ff7tkQmlGallery/main.qml
- src/CMakeLists.txt
- src/ff7tkQuick/Controls/CMakeLists.txt
- src/ff7tkQuick/Controls/ItemSelector.qml
- src/ff7tkQuick/Controls/MateriaEditor.qml
- translations/ff7tk_de.ts
- translations/ff7tk_en.ts
- translations/ff7tk_es.ts
- translations/ff7tk_fr.ts
- translations/ff7tk_it.ts
- translations/ff7tk_ja.ts
- translations/ff7tk_pl.ts
- translations/ff7tk_re.ts
- unittests/data/FF7Char_test.h
- Improve Framework building
- New: Qml Control `ItemSelector`
> Fw2 update and Qml itemselector

- src/data/FF7FieldItemList.h
- src/data/FF7Save.cpp
- src/data/FF7Save.h
- src/data/FF7Save_Types.h
- translations/ff7tk_de.ts
- translations/ff7tk_en.ts
- translations/ff7tk_es.ts
- translations/ff7tk_fr.ts
- translations/ff7tk_it.ts
- translations/ff7tk_ja.ts
- translations/ff7tk_pl.ts
- translations/ff7tk_re.ts
- Added Missing items from field item list
- Handle Battle Arena Special Wins
> Add missing save info reported by Raziel80 

- .github/workflows/build.yml
- demos/ff7tkQmlGallery/CMakeLists.txt
- demos/ff7tkQmlGallery/PaletteView.qml
- demos/ff7tkQmlGallery/main.qml
- demos/ff7tkQmlGallery/qml.qrc
- src/ff7tkQuick/Controls/Components/ApplicationWindow.qml
- src/ff7tkQuick/Controls/ItemPreview.qml
- src/ff7tkQuick/Controls/MateriaEditor.qml
- Fix up a  missing call for added Status
- Add palette view to the qml demo 
- Work to use better palette choices
> Qml improvements

- demos/ff7tkQmlGallery/main.qml
- src/ff7tkQuick/Controls/MateriaEditor.qml
- src/ff7tkQuick/DataTypes/ff7tkQuickDataTypes.h
> Small Qml Cleanups

- .github/workflows/build.yml
> ci: bump install-qt-action to 4

- src/data/FF7Save.cpp
- src/data/FF7Save.h
- src/data/FF7Save_Types.h
- Start to clean up style of ff7Save
- Begin to provide some functionality in FF7SLOT
> Begin FF7Save cleanup

- src/widgets/data/CharEditor.cpp
- src/widgets/data/ChocoboEditor.cpp
- src/widgets/data/ChocoboLabel.cpp
- src/widgets/data/ChocoboManager.cpp
- src/widgets/data/ItemListView.cpp
- src/widgets/data/ItemPreview.cpp
- src/widgets/data/LocationViewer.cpp
- src/widgets/data/MateriaEditor.cpp
- src/widgets/data/MenuListWidget.cpp
- src/widgets/data/SlotSelect.cpp
> refactor: clean up style on widgets

- demos/ff7tkWidgetGallery/mainwindow.cpp
- demos/ff7tkWidgetGallery/mainwindow.h
- demos/ff7tkWidgetGallery/mainwindow.ui
- src/data/FF7Materia.h
- src/widgets/data/CharEditor.cpp
- src/widgets/data/MateriaEditor.cpp
- Allow for materia ids between 91 - 254 for mods that add new materia after the last ones id.
- Add checks for this in the materia editor and add these id's to the placeholder list. Allowing basic editing of these materias
> Ex materia

- .github/workflows/build.yml
Bump to Qt 6.8.2 for "generic bulid"
> ci: Qt 682

- src/widgets/data/CharEditor.cpp
> fix: ChararacterEditor not emitting limit2Changed

- src/widgets/data/MateriaEditor.cpp
> fix: MateriaEditor: check

- translations/CMakeLists.txt
- translations/ff7tk_zh.ts
Add chinese translations from https://github.com/sithlord48/blackchocobo/issues/104
> feat: add Chinese translation

- .github/workflows/build.yml
- src/data/CMakeLists.txt
- Build arm ifw installer and generic tar ball to use later for appimages
- Build windows arm (required ifw for win_arm first)
> ci: add arm builds
